---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: account
data: “111111,222222,333333,444444,555555,666666,777777"

---
spring:
  profiles: amount
data: "1000,2000,3000,4000,5000,6000,7000"

---
spring:
  profiles: beneficiary
data: Mahesh,Rune,Ganesh,Vijay

---
spring:
  profiles: currency
data: INR,DKK,SEK,AUR,USD,CAD

---
spring:
  profiles: payee
data: Johan,Jan

---
spring:
  profiles: subject
name: Sachin
  
---
spring:
  profiles: verb
name: knew,had,saw,bought

---
spring:
  profiles: article
name: a,the

---
spring:
  profiles: adjective
name: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
name: boat,book,vote,seat,backpack,partition,groundhog
  
