# This single codebase performs generating of subject, verb, article, adjective, and noun, plus sentence assembly.
# True microservices would have separate codebases, but for our purposes a single codebase is fine.
# Run by opening 6 separate command prompts:
# java -jar -Dspring.profiles.active=subject session-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=verb session-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=article session-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=adjective session-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=noun session-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=sentence session-4-eureka-client-solution-0.0.1-SNAPSHOT.jar

---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

amounts: "1000,2000,3000,4000,5000,6000,7000"
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

